// THE INDICATOR — prototype demo dataset (2026 NFL season)
// NOTE: All values here are illustrative SAMPLE/PROTOTYPE data generated for
// demonstration. Roster names and teams were matched against the Sleeper player directory on 2026-09-19.
// All metrics, narratives, signals and projections are fabricated examples, NOT verified live statistics.

export type Position = 'QB' | 'RB' | 'WR' | 'TE'
export type Trend = 'Rising' | 'Falling' | 'Stable'

export type SignalType =
  | 'STRONG BUY'
  | 'BUY'
  | 'WATCH'
  | 'HOLD'
  | 'SELL'
  | 'BREAKOUT ALERT'
  | 'ROLE CHANGE'
  | 'INJURY OPPORTUNITY'

export interface ValuePoint {
  week: string
  value: number
}

export interface Player {
  id: string
  name: string
  team: string
  position: Position
  indicatorScore: number // 0-100
  scoreDelta: number // change in indicator score over trailing window
  trend: Trend
  fantasyValue: number // underlying market value (price-like index)
  valueDeltaPct: number // % change over trailing window
  predictedPPG: number
  // Component scores (0-100)
  opportunityMomentum: number
  efficiency: number
  roleSecurity: number
  matchup: number
  injuryEnvironment: number
  // Usage metrics
  snapPct: number
  routeParticipation: number
  targetShare: number
  airYardShare: number
  redZoneUsage: number // opportunities inside the 20 (trailing)
  carries: number
  targets: number
  explosivePlays: number
  rationale: string
  signal: SignalType
  history: ValuePoint[]
}

// ---- deterministic history generator ----
function seeded(seed: number) {
  let s = seed % 2147483647
  if (s <= 0) s += 2147483646
  return () => (s = (s * 16807) % 2147483647) / 2147483647
}

const WEEKS = ['W1', 'W2', 'W3', 'W4', 'W5', 'W6', 'W7', 'W8', 'W9', 'Now']

function makeHistory(seed: number, start: number, end: number, vol: number): ValuePoint[] {
  const rand = seeded(seed)
  const n = WEEKS.length
  return WEEKS.map((week, i) => {
    const t = i / (n - 1)
    const base = start + (end - start) * t
    const noise = (rand() - 0.5) * 2 * vol
    const value = Math.max(1, Math.round((base + noise) * 10) / 10)
    return { week, value }
  })
}

// ---- roster ----
export const players: Player[] = [
  {
    id: 'caleb-douglas',
    name: 'Caleb Douglas',
    team: 'MIA',
    position: 'WR',
    indicatorScore: 78,
    scoreDelta: 14,
    trend: 'Rising',
    fantasyValue: 41.6,
    valueDeltaPct: 22.4,
    predictedPPG: 13.8,
    opportunityMomentum: 84,
    efficiency: 71,
    roleSecurity: 62,
    matchup: 74,
    injuryEnvironment: 88,
    snapPct: 68,
    routeParticipation: 79,
    targetShare: 21,
    airYardShare: 34,
    redZoneUsage: 5,
    carries: 1,
    targets: 24,
    explosivePlays: 6,
    signal: 'STRONG BUY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(11, 30, 41.6, 2.4),
  },
  {
    id: 'terry-mclaurin',
    name: 'Terry McLaurin',
    team: 'WAS',
    position: 'WR',
    indicatorScore: 71,
    scoreDelta: 9,
    trend: 'Rising',
    fantasyValue: 36.2,
    valueDeltaPct: 15.1,
    predictedPPG: 12.1,
    opportunityMomentum: 77,
    efficiency: 74,
    roleSecurity: 58,
    matchup: 69,
    injuryEnvironment: 82,
    snapPct: 61,
    routeParticipation: 72,
    targetShare: 18,
    airYardShare: 27,
    redZoneUsage: 4,
    carries: 2,
    targets: 19,
    explosivePlays: 5,
    signal: 'BUY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(22, 28, 36.2, 2.1),
  },
  {
    id: 'jahmyr-gibbs',
    name: 'Jahmyr Gibbs',
    team: 'DET',
    position: 'RB',
    indicatorScore: 91,
    scoreDelta: 3,
    trend: 'Stable',
    fantasyValue: 72.4,
    valueDeltaPct: 2.9,
    predictedPPG: 19.6,
    opportunityMomentum: 88,
    efficiency: 90,
    roleSecurity: 94,
    matchup: 66,
    injuryEnvironment: 79,
    snapPct: 74,
    routeParticipation: 58,
    targetShare: 12,
    airYardShare: 8,
    redZoneUsage: 12,
    carries: 118,
    targets: 28,
    explosivePlays: 11,
    signal: 'HOLD',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(33, 68, 72.4, 1.8),
  },
  {
    id: 'nico-collins',
    name: 'Nico Collins',
    team: 'HOU',
    position: 'WR',
    indicatorScore: 83,
    scoreDelta: 6,
    trend: 'Rising',
    fantasyValue: 58.1,
    valueDeltaPct: 9.8,
    predictedPPG: 16.4,
    opportunityMomentum: 81,
    efficiency: 85,
    roleSecurity: 88,
    matchup: 72,
    injuryEnvironment: 90,
    snapPct: 89,
    routeParticipation: 92,
    targetShare: 29,
    airYardShare: 41,
    redZoneUsage: 8,
    carries: 0,
    targets: 47,
    explosivePlays: 9,
    signal: 'BUY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(44, 49, 58.1, 2.0),
  },
  {
    id: 'braelon-allen',
    name: 'Braelon Allen',
    team: 'NYJ',
    position: 'RB',
    indicatorScore: 44,
    scoreDelta: -17,
    trend: 'Falling',
    fantasyValue: 33.9,
    valueDeltaPct: -19.6,
    predictedPPG: 9.2,
    opportunityMomentum: 38,
    efficiency: 51,
    roleSecurity: 33,
    matchup: 47,
    injuryEnvironment: 64,
    snapPct: 42,
    routeParticipation: 31,
    targetShare: 7,
    airYardShare: 4,
    redZoneUsage: 3,
    carries: 71,
    targets: 14,
    explosivePlays: 2,
    signal: 'SELL',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(55, 42, 33.9, 2.2),
  },
  {
    id: 'jayden-reed',
    name: 'Jayden Reed',
    team: 'GB',
    position: 'WR',
    indicatorScore: 66,
    scoreDelta: 11,
    trend: 'Rising',
    fantasyValue: 39.7,
    valueDeltaPct: 13.4,
    predictedPPG: 11.7,
    opportunityMomentum: 73,
    efficiency: 68,
    roleSecurity: 55,
    matchup: 78,
    injuryEnvironment: 61,
    snapPct: 64,
    routeParticipation: 70,
    targetShare: 19,
    airYardShare: 24,
    redZoneUsage: 6,
    carries: 0,
    targets: 22,
    explosivePlays: 4,
    signal: 'BREAKOUT ALERT',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(66, 31, 39.7, 2.6),
  },
  {
    id: 'mike-washington',
    name: 'Mike Washington',
    team: 'LV',
    position: 'RB',
    indicatorScore: 59,
    scoreDelta: 21,
    trend: 'Rising',
    fantasyValue: 28.4,
    valueDeltaPct: 34.2,
    predictedPPG: 10.8,
    opportunityMomentum: 82,
    efficiency: 63,
    roleSecurity: 41,
    matchup: 58,
    injuryEnvironment: 45,
    snapPct: 49,
    routeParticipation: 44,
    targetShare: 11,
    airYardShare: 6,
    redZoneUsage: 7,
    carries: 58,
    targets: 17,
    explosivePlays: 5,
    signal: 'ROLE CHANGE',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(77, 21, 28.4, 2.3),
  },
  {
    id: 'jordan-mason',
    name: 'Jordan Mason',
    team: 'MIN',
    position: 'RB',
    indicatorScore: 38,
    scoreDelta: 27,
    trend: 'Rising',
    fantasyValue: 19.8,
    valueDeltaPct: 41.0,
    predictedPPG: 8.4,
    opportunityMomentum: 69,
    efficiency: 57,
    roleSecurity: 28,
    matchup: 62,
    injuryEnvironment: 38,
    snapPct: 34,
    routeParticipation: 29,
    targetShare: 8,
    airYardShare: 3,
    redZoneUsage: 4,
    carries: 39,
    targets: 9,
    explosivePlays: 3,
    signal: 'INJURY OPPORTUNITY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(88, 14, 19.8, 2.1),
  },
  {
    id: 'cade-otton',
    name: 'Cade Otton',
    team: 'TB',
    position: 'TE',
    indicatorScore: 74,
    scoreDelta: 8,
    trend: 'Rising',
    fantasyValue: 44.9,
    valueDeltaPct: 11.2,
    predictedPPG: 12.6,
    opportunityMomentum: 76,
    efficiency: 80,
    roleSecurity: 84,
    matchup: 70,
    injuryEnvironment: 86,
    snapPct: 86,
    routeParticipation: 81,
    targetShare: 22,
    airYardShare: 26,
    redZoneUsage: 9,
    carries: 0,
    targets: 33,
    explosivePlays: 4,
    signal: 'BUY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(99, 36, 44.9, 1.9),
  },
  {
    id: 'justin-herbert',
    name: 'Justin Herbert',
    team: 'LAC',
    position: 'QB',
    indicatorScore: 80,
    scoreDelta: 5,
    trend: 'Rising',
    fantasyValue: 55.3,
    valueDeltaPct: 7.6,
    predictedPPG: 22.4,
    opportunityMomentum: 78,
    efficiency: 83,
    roleSecurity: 96,
    matchup: 75,
    injuryEnvironment: 84,
    snapPct: 100,
    routeParticipation: 0,
    targetShare: 0,
    airYardShare: 0,
    redZoneUsage: 6,
    carries: 21,
    targets: 0,
    explosivePlays: 14,
    signal: 'BUY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(111, 48, 55.3, 1.7),
  },
  {
    id: 'ja-marr-chase',
    name: "Ja'Marr Chase",
    team: 'CIN',
    position: 'WR',
    indicatorScore: 88,
    scoreDelta: 1,
    trend: 'Stable',
    fantasyValue: 69.2,
    valueDeltaPct: 1.4,
    predictedPPG: 17.9,
    opportunityMomentum: 85,
    efficiency: 89,
    roleSecurity: 92,
    matchup: 60,
    injuryEnvironment: 87,
    snapPct: 93,
    routeParticipation: 95,
    targetShare: 31,
    airYardShare: 38,
    redZoneUsage: 10,
    carries: 1,
    targets: 52,
    explosivePlays: 12,
    signal: 'HOLD',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(122, 66, 69.2, 1.5),
  },
  {
    id: 'jaxon-smith-njigba',
    name: 'Jaxon Smith-Njigba',
    team: 'SEA',
    position: 'WR',
    indicatorScore: 52,
    scoreDelta: -13,
    trend: 'Falling',
    fantasyValue: 34.1,
    valueDeltaPct: -14.8,
    predictedPPG: 9.9,
    opportunityMomentum: 44,
    efficiency: 58,
    roleSecurity: 49,
    matchup: 41,
    injuryEnvironment: 74,
    snapPct: 71,
    routeParticipation: 74,
    targetShare: 16,
    airYardShare: 19,
    redZoneUsage: 2,
    carries: 0,
    targets: 30,
    explosivePlays: 3,
    signal: 'SELL',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(133, 41, 34.1, 2.0),
  },
  {
    id: 'jaylen-wright',
    name: 'Jaylen Wright',
    team: 'MIA',
    position: 'RB',
    indicatorScore: 63,
    scoreDelta: 4,
    trend: 'Stable',
    fantasyValue: 42.0,
    valueDeltaPct: 3.1,
    predictedPPG: 12.9,
    opportunityMomentum: 64,
    efficiency: 72,
    roleSecurity: 70,
    matchup: 68,
    injuryEnvironment: 66,
    snapPct: 63,
    routeParticipation: 52,
    targetShare: 13,
    airYardShare: 7,
    redZoneUsage: 8,
    carries: 96,
    targets: 26,
    explosivePlays: 6,
    signal: 'WATCH',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(144, 40, 42.0, 1.6),
  },
  {
    id: 'cole-kmet',
    name: 'Cole Kmet',
    team: 'CHI',
    position: 'TE',
    indicatorScore: 48,
    scoreDelta: 16,
    trend: 'Rising',
    fantasyValue: 22.7,
    valueDeltaPct: 24.9,
    predictedPPG: 8.1,
    opportunityMomentum: 71,
    efficiency: 55,
    roleSecurity: 46,
    matchup: 64,
    injuryEnvironment: 58,
    snapPct: 67,
    routeParticipation: 63,
    targetShare: 15,
    airYardShare: 14,
    redZoneUsage: 5,
    carries: 0,
    targets: 21,
    explosivePlays: 2,
    signal: 'WATCH',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(155, 18, 22.7, 2.4),
  },
  {
    id: 'rj-harvey',
    name: 'RJ Harvey',
    team: 'DEN',
    position: 'RB',
    indicatorScore: 55,
    scoreDelta: -9,
    trend: 'Falling',
    fantasyValue: 37.5,
    valueDeltaPct: -10.7,
    predictedPPG: 10.4,
    opportunityMomentum: 48,
    efficiency: 61,
    roleSecurity: 52,
    matchup: 53,
    injuryEnvironment: 43,
    snapPct: 57,
    routeParticipation: 47,
    targetShare: 10,
    airYardShare: 5,
    redZoneUsage: 6,
    carries: 84,
    targets: 15,
    explosivePlays: 4,
    signal: 'SELL',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(166, 44, 37.5, 1.9),
  },
  {
    id: 'ceedee-lamb',
    name: 'CeeDee Lamb',
    team: 'DAL',
    position: 'WR',
    indicatorScore: 69,
    scoreDelta: 7,
    trend: 'Rising',
    fantasyValue: 46.8,
    valueDeltaPct: 8.9,
    predictedPPG: 13.2,
    opportunityMomentum: 74,
    efficiency: 76,
    roleSecurity: 66,
    matchup: 71,
    injuryEnvironment: 80,
    snapPct: 78,
    routeParticipation: 82,
    targetShare: 23,
    airYardShare: 29,
    redZoneUsage: 6,
    carries: 0,
    targets: 35,
    explosivePlays: 7,
    signal: 'BUY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(177, 39, 46.8, 1.8),
  },
  {
    id: 'trey-benson',
    name: 'Trey Benson',
    team: 'ARI',
    position: 'RB',
    indicatorScore: 34,
    scoreDelta: 19,
    trend: 'Rising',
    fantasyValue: 15.2,
    valueDeltaPct: 38.5,
    predictedPPG: 6.8,
    opportunityMomentum: 66,
    efficiency: 49,
    roleSecurity: 22,
    matchup: 55,
    injuryEnvironment: 31,
    snapPct: 27,
    routeParticipation: 24,
    targetShare: 6,
    airYardShare: 2,
    redZoneUsage: 3,
    carries: 31,
    targets: 7,
    explosivePlays: 2,
    signal: 'INJURY OPPORTUNITY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(188, 11, 15.2, 2.0),
  },
  {
    id: 'brian-thomas',
    name: 'Brian Thomas',
    team: 'JAX',
    position: 'WR',
    indicatorScore: 61,
    scoreDelta: 12,
    trend: 'Rising',
    fantasyValue: 35.0,
    valueDeltaPct: 16.8,
    predictedPPG: 11.0,
    opportunityMomentum: 75,
    efficiency: 66,
    roleSecurity: 54,
    matchup: 73,
    injuryEnvironment: 69,
    snapPct: 66,
    routeParticipation: 73,
    targetShare: 20,
    airYardShare: 31,
    redZoneUsage: 4,
    carries: 0,
    targets: 27,
    explosivePlays: 6,
    signal: 'BREAKOUT ALERT',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(199, 30, 35.0, 2.5),
  },
  {
    id: 'saquon-barkley',
    name: 'Saquon Barkley',
    team: 'PHI',
    position: 'RB',
    indicatorScore: 86,
    scoreDelta: 2,
    trend: 'Stable',
    fantasyValue: 64.8,
    valueDeltaPct: 2.2,
    predictedPPG: 18.1,
    opportunityMomentum: 83,
    efficiency: 84,
    roleSecurity: 90,
    matchup: 69,
    injuryEnvironment: 82,
    snapPct: 71,
    routeParticipation: 55,
    targetShare: 11,
    airYardShare: 6,
    redZoneUsage: 13,
    carries: 121,
    targets: 24,
    explosivePlays: 9,
    signal: 'HOLD',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(210, 62, 64.8, 1.6),
  },
  {
    id: 'michael-penix',
    name: 'Michael Penix',
    team: 'ATL',
    position: 'QB',
    indicatorScore: 57,
    scoreDelta: -11,
    trend: 'Falling',
    fantasyValue: 43.2,
    valueDeltaPct: -12.3,
    predictedPPG: 17.2,
    opportunityMomentum: 51,
    efficiency: 55,
    roleSecurity: 88,
    matchup: 39,
    injuryEnvironment: 72,
    snapPct: 100,
    routeParticipation: 0,
    targetShare: 0,
    airYardShare: 0,
    redZoneUsage: 4,
    carries: 12,
    targets: 0,
    explosivePlays: 6,
    signal: 'SELL',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(221, 49, 43.2, 1.8),
  },
  {
    id: 'khalil-shakir',
    name: 'Khalil Shakir',
    team: 'BUF',
    position: 'WR',
    indicatorScore: 64,
    scoreDelta: 10,
    trend: 'Rising',
    fantasyValue: 38.9,
    valueDeltaPct: 12.6,
    predictedPPG: 11.4,
    opportunityMomentum: 72,
    efficiency: 70,
    roleSecurity: 57,
    matchup: 76,
    injuryEnvironment: 78,
    snapPct: 62,
    routeParticipation: 71,
    targetShare: 18,
    airYardShare: 22,
    redZoneUsage: 7,
    carries: 1,
    targets: 23,
    explosivePlays: 5,
    signal: 'BUY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(232, 34, 38.9, 2.0),
  },
  {
    id: 'kendre-miller',
    name: 'Kendre Miller',
    team: 'NO',
    position: 'RB',
    indicatorScore: 41,
    scoreDelta: 23,
    trend: 'Rising',
    fantasyValue: 21.3,
    valueDeltaPct: 36.1,
    predictedPPG: 8.9,
    opportunityMomentum: 70,
    efficiency: 60,
    roleSecurity: 35,
    matchup: 60,
    injuryEnvironment: 40,
    snapPct: 38,
    routeParticipation: 33,
    targetShare: 9,
    airYardShare: 4,
    redZoneUsage: 5,
    carries: 44,
    targets: 12,
    explosivePlays: 4,
    signal: 'INJURY OPPORTUNITY',
    rationale: 'Illustrative player scenario. Usage, score and projection shown here are sample values, not measured performance or advice.',
    history: makeHistory(243, 16, 21.3, 2.3),
  },
]

export function getPlayer(id: string): Player | undefined {
  return players.find((p) => p.id === id)
}

// ---- derived collections for the Market dashboard ----
const byScoreDeltaDesc = (a: Player, b: Player) => b.scoreDelta - a.scoreDelta
const byValueDeltaDesc = (a: Player, b: Player) => b.valueDeltaPct - a.valueDeltaPct

export const marketRisers = [...players].sort(byValueDeltaDesc).slice(0, 5)
export const marketFallers = [...players].sort((a, b) => a.valueDeltaPct - b.valueDeltaPct).slice(0, 5)

export const buySignals = players
  .filter((p) => p.signal === 'STRONG BUY' || p.signal === 'BUY')
  .sort(byScoreDeltaDesc)
export const sellSignals = players.filter((p) => p.signal === 'SELL').sort((a, b) => a.scoreDelta - b.scoreDelta)
export const breakoutWatch = players.filter((p) => p.signal === 'BREAKOUT ALERT').sort(byScoreDeltaDesc)
export const roleChanges = players.filter((p) => p.signal === 'ROLE CHANGE').sort(byScoreDeltaDesc)
export const injuryOpportunities = players
  .filter((p) => p.signal === 'INJURY OPPORTUNITY')
  .sort(byScoreDeltaDesc)
export const waiverTargets = players
  .filter((p) => p.fantasyValue < 40 && p.trend === 'Rising')
  .sort(byValueDeltaDesc)
  .slice(0, 6)

// ---- hypothetical handcuff examples, not verified depth charts ----
export interface Handcuff {
  id: string
  backupId: string
  starterName: string
  starterTeam: string
  standaloneValue: number // current value with starter healthy
  inheritValue: number // projected value if starter misses time
  note: string
}

export const handcuffs: Handcuff[] = [
  {
    id: 'hc-morrison',
    backupId: 'mike-washington',
    starterName: 'hypothetical starter',
    starterTeam: 'LV',
    standaloneValue: 28.4,
    inheritValue: 74.0,
    note: 'Sample contingency scenario. Confirm current depth chart and player availability before making roster decisions.',
  },
  {
    id: 'hc-olsson',
    backupId: 'jordan-mason',
    starterName: 'hypothetical starter',
    starterTeam: 'MIN',
    standaloneValue: 19.8,
    inheritValue: 66.5,
    note: 'Sample contingency scenario. Confirm current depth chart and player availability before making roster decisions.',
  },
  {
    id: 'hc-sandoval',
    backupId: 'trey-benson',
    starterName: 'hypothetical starter',
    starterTeam: 'ARI',
    standaloneValue: 15.2,
    inheritValue: 58.9,
    note: 'Sample contingency scenario. Confirm current depth chart and player availability before making roster decisions.',
  },
  {
    id: 'hc-baptiste',
    backupId: 'kendre-miller',
    starterName: 'hypothetical starter',
    starterTeam: 'NO',
    standaloneValue: 21.3,
    inheritValue: 61.7,
    note: 'Sample contingency scenario. Confirm current depth chart and player availability before making roster decisions.',
  },
  {
    id: 'hc-huang',
    backupId: 'jaylen-wright',
    starterName: 'hypothetical starter',
    starterTeam: 'MIA',
    standaloneValue: 42.0,
    inheritValue: 63.2,
    note: 'Sample contingency scenario. Confirm current depth chart and player availability before making roster decisions.',
  },
  {
    id: 'hc-boone',
    backupId: 'braelon-allen',
    starterName: 'hypothetical starter',
    starterTeam: 'NYJ',
    standaloneValue: 33.9,
    inheritValue: 44.1,
    note: 'Sample contingency scenario. Confirm current depth chart and player availability before making roster decisions.',
  },
]

// ---- signals feed ----
export interface SignalEvent {
  id: string
  type: SignalType
  playerId: string
  when: string
  headline: string
  detail: string
}

export const signalFeed: SignalEvent[] = [
  {
    id: 's1',
    type: 'STRONG BUY',
    playerId: 'caleb-douglas',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's2',
    type: 'ROLE CHANGE',
    playerId: 'mike-washington',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's3',
    type: 'BREAKOUT ALERT',
    playerId: 'jayden-reed',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's4',
    type: 'SELL',
    playerId: 'braelon-allen',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's5',
    type: 'INJURY OPPORTUNITY',
    playerId: 'jordan-mason',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's6',
    type: 'BUY',
    playerId: 'nico-collins',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's7',
    type: 'BREAKOUT ALERT',
    playerId: 'brian-thomas',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's8',
    type: 'SELL',
    playerId: 'jaxon-smith-njigba',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's9',
    type: 'BUY',
    playerId: 'cade-otton',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's10',
    type: 'WATCH',
    playerId: 'cole-kmet',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's11',
    type: 'INJURY OPPORTUNITY',
    playerId: 'kendre-miller',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's12',
    type: 'HOLD',
    playerId: 'ja-marr-chase',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
  {
    id: 's13',
    type: 'BUY',
    playerId: 'terry-mclaurin',
    when: 'Sample',
    headline: 'Illustrative signal scenario',
    detail: 'Example of how a signal could be presented once verified usage data is connected.',
  },
]
