const assert=require('node:assert/strict'); const fs=require('node:fs'); const ts=require('typescript'); const vm=require('node:vm');
const code=ts.transpileModule(fs.readFileSync(require('node:path').join(__dirname,'live-schedule.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const scheduleExports={}; vm.runInNewContext(code,{exports:scheduleExports,require:()=>({unstable_cache:f=>f}),Date,Intl,Set,Object,fetch:async()=>{throw Error('offline')},AbortSignal,Error});
const now=Date.parse('2026-10-05T05:00:00Z'); const game=(id,date,overrides={})=>({id,date,season:{type:2},links:[{href:'https://www.espn.com/nfl/game/'+id}],competitions:[{timeValid:true,competitors:[{homeAway:'home',team:{abbreviation:'LAC'}},{homeAway:'away',team:{abbreviation:'WSH'}}]}],...overrides});
const valid=[1,2,3,4,5].map(i=>game(String(i),`2026-10-${10+i}T20:00:00Z`));
const invalid=[game('past','2026-01-01T20:00:00Z'),game('bad','invalid'),game('pre','2026-10-20T20:00:00Z',{season:{type:1}}),game('unsafe','2026-10-20T20:00:00Z',{links:[{href:'https://notespn.com/'}]}),game('canceled','2026-10-20T20:00:00Z',{competitions:[{...valid[0].competitions[0],status:{type:{name:'STATUS_CANCELED'}}}]}),game('incomplete','2026-10-20T20:00:00Z',{competitions:[{competitors:[]}]} )];
const result=scheduleExports.parseUpcomingGames([...valid.reverse(),valid.at(-1),...invalid],now); assert.equal(result.LAC.length,4); assert.deepEqual(JSON.parse(JSON.stringify(result.LAC.map(g=>g.id))),['1','2','3','4']);assert.equal(result.LAC[0].opponent,'WAS');assert.equal(result.LAC[0].home,true);assert.equal(result.WAS[0].opponent,'LAC');assert.equal(result.WAS[0].home,false);assert.equal(Object.keys(scheduleExports.parseUpcomingGames([],now)).length,0);
const evening=scheduleExports.parseUpcomingGames([game('night','2026-11-18T01:15:00Z')],now);assert.equal(evening.LAC[0].dateLabel,'Nov 17');
scheduleExports.getLiveSchedule().then(result=>{assert.equal(Object.keys(result.byTeam).length,0); console.log('PASS schedule: future only, source validation, canceled/malformed exclusion, duplicate suppression, home/away, four-game limit, timezone dates, team normalization, offline UNKNOWN');});
